version: "3.5"
services:
  pgadmin4:
    image: "dpage/pgadmin4:${PG_ADMIN_TAG}"
    container_name: "pgadmin4"
    ports:
#      - $PG_ADMIN_PORT:443
      - $PG_ADMIN_PORT:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
#      - ./.certs/certificate.cert:/certs/server.cert
#      - ./.certs/certificate.key:/certs/server.key
    environment:
#      - "PGADMIN_ENABLE_TLS=True"
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}"
